### PR TITLE
Reverted changes in update_checksum and verify_checksum

### LINKED ISSUE #45: Sensorcal not working
I've built the latest image and found sensorcal is not working.
It finds sensorboard as virgin and asks to initialize (even when the sensorboard is been calibrated before).
I clicked on "yes" to initialize the board again, but keeps seeing the board as virgin.
I ran sensorcal -c. The output is "EEPROM content not valid, run sensorcal -i" 
I ran sensorcal -i and seems to run OK.
I suspect it has something to do with Checksum calculation or verification.
Running sensorcal -d The output is "EEPROM content not valid, run sensorcal -i" twice
From sensorcal:
```

		case 'd':
				// read actual EEPROM values
				printf("Reading EEPROM values ...\n\n");
				if( eeprom_read_data(&eeprom, &data) == 0)
				{
				  memcpy(sn,data.serial,6);
					printf("Actual EEPROM values:\n");
					printf("---------------------\n");
					printf("Serial: \t\t\t%s\n", sn);
					printf("Differential pressure offset:\t%f\n",data.zero_offset);
				}
				else
				{
					printf("EEPROM content not valid !!\n");
					printf("Please use -i to initialize EEPROM !!\n");
					exit_code=2;
					break;
				}
```
from 24c16.cpp
```
int eeprom_read_data(t_24c16 *eeprom, t_eeprom_data *data)
{
	// read eeprom data to struct
	if (eeprom_read(eeprom, (char*)data, 0x00, sizeof(*data))==1)
		return 1;						// Failed to read the EEPROM

	// verify checksum
	if (!verify_checksum(data))
	{
		printf("EEPROM content not valid !!\n");
		printf("Please use -i to initialize EEPROM !!\n");
		return 2;
	}
	else
	{
		return 0;
	}
}
```
It seems to be returning 2 and printing error message twice as eeprom_read() is not printing error messages.

### PR DESCRIPTION
**Pull request by iglesiasmarianod**
fixes openvario/meta-openvario#285

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This revert is wrong, do **not** merge! It does not "fix" anything, it only makes a symptom go away, but ignores the reason for for this symptom (and doesn't explain anything in the commit message).

`sizeof(data) == 4`, so this checksums only the first 4 bytes of this struct (i.e. the 3-byte header plus the `version` field). If it were correct to only checksum the first 4 bytes, it wouldn't use the size of a pointer for this (which is 8 on 64 bit CPUs).

Note that there are two padding bytes in this struct; the way it was initially authored is pretty clumsy. This padding could maybe cause the problem (just a random guess).

**Comment by MaxKellermann** [comment]
I have a better guess what's the problem here: the "crc" field is included in the CRC calculation. This was not a problem before because only the first 4 bytes were used before. Both is buggy, my recent change only made this problem visible.

**Comment by iglesiasmarianod** [comment]
Thanks @MaxKellermann for checking this. Do you want me to close the PR?
I already went back to your changes and will test uncommenting the outputs.

**Comment by linuxianer99** [comment]
@iglesiasmarianod
Think the problem is in 
update_checksum function in 24c16.c. As Max mentioned, the checksum is included in the checksum ;-) I will have a look on this ...
 You can close this PR ...

**Comment by iglesiasmarianod** [comment]
Thanks @linuxianer99 I'll close it. If you need to test I have a complete 5.7" OV at home.

**Pull request closed without merging**
