### PR TITLE
Some basic code cleanup

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Review by linuxianer99 — APPROVED** [review]
Looks ok :-)

**Comment by linuxianer99** [comment]
@MaxKellermann : Does it make sense, to switch to cMake ?? 
I did some tests a while ago .. the main reason was, to use a software test framework ... https://github.com/linuxianer99/sensord/tree/cmake

What do you think ??

**Comment by MaxKellermann** [comment]
I prefer Meson over cmake, but anything is better than a plain Makefile.

**Comment by MaxKellermann** [comment]
@kedder?

**Review by kedder — APPROVED** [review]
LGTM

**Pull request merged**
