### PR TITLE
Code cleanup & inetd mode

### PR DESCRIPTION
**Pull request by MaxKellermann**
The inetd mode allows launching sensord with systemd socket activation; this switches sensord from a variod client to a server which listens for an incoming connection from variod.
I will submit a variod PR to implement this, and then we do the switch in the OpenVario firmware. Until then, sensord works just as before, unless one specified the new `-i` option.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Codacy warnings are obviously bogus.

**Review by linuxianer99 — APPROVED** [review]
LGTM

**Review by kedder — APPROVED** [review]
LGTM

**Comment by MaxKellermann** [comment]
@linuxianer99?
I'm waiting for this and https://github.com/Openvario/variod/pull/44 and after that I'll finish https://github.com/Openvario/meta-openvario/pull/284
These 3 PRs need some coordination; there will be a brief period of breakage.

**Comment by linuxianer99** [comment]
@MaxKellermann : both are merged ...

Sorry ... bit busy this week ...

**Comment by MaxKellermann** [comment]
Thanks - I know how busy weeks feel. I've just had the busiest 2 weeks *ever*.
I'll try to finish the recipes today.

**Comment by linuxianer99** [comment]
No hurry ... We all have "a normal life" beside this open source development as well ;-)

Thanks for all your time and effort you are putting to this project !!

**Pull request merged**
